services:
  qdrant1:
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    image: lr-qdrant:1.0.0
    restart: unless-stopped
    # Первая нода инициализирует кластер, аргумент --bootstrap ей не нужен
    command: ["./qdrant", "--uri", "http://qdrant1:6335"]
    ports:
      - 6333:6333
    configs:
      - source: qdrant-config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant-data-1:/qdrant/storage # У каждого узла должен быть свой volume!
      - ./config.yaml:/qdrant/config/config.yaml
    networks:
      - qdrant-net

  qdrant2:
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    image: lr-qdrant:1.0.0
    restart: unless-stopped
    # Подключается к первой ноде через --bootstrap
    command: ["./qdrant", "--uri", "http://qdrant2:6335", "--bootstrap", "http://qdrant1:6335"]
    ports:
      - 16333:6333
    configs:
      - source: qdrant-config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant-data-2:/qdrant/storage
      - ./config.yaml:/qdrant/config/config.yaml
    depends_on:
      - qdrant1
    networks:
      - qdrant-net

  qdrant3:
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    image: lr-qdrant:1.0.0
    restart: unless-stopped
    # Также подключается к первой ноде
    command: ["./qdrant", "--uri", "http://qdrant3:6335", "--bootstrap", "http://qdrant1:6335"]
    ports:
      - 26333:6333
    configs:
      - source: qdrant-config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant-data-3:/qdrant/storage
      - ./config.yaml:/qdrant/config/config.yaml
    depends_on:
      - qdrant1
    networks:
      - qdrant-net

  qdrant-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: lr-qdrant-test:1.0.0
    command: tail -f /dev/null
    environment:
      - QDRANT_URL=http://qdrant1:6333
    depends_on:
      - qdrant1
      - qdrant2
      - qdrant3
    networks:
      - qdrant-net
    volumes:
      - ./:/app
      - qdrant-data-1:/qdrant/storage-1
      - qdrant-data-2:/qdrant/storage-2
      - qdrant-data-3:/qdrant/storage-3
#      - /var/run/docker.sock:/var/run/docker.sock

networks:
  qdrant-net:

# Важно: раздельные volume для каждой ноды, иначе данные перезапишут друг друга
volumes:
  qdrant-data-1:
  qdrant-data-2:
  qdrant-data-3:

configs:
  qdrant-config:
    content: |
      log_level: INFO
